<?php 

$websites = array (	   	
	"http://www.greenpeace.org/international"  =>  "International (English)",
	"http://www.greenpeace.org/afrique/"  =>  "Africa - Congo (Français)",
	"http://www.greenpeace.org/afrique/"  =>  "Africa - Senegal (Français)",
	"http://www.greenpeace.org/africa/"  =>  "Africa - South Africa (English)",
	"http://www.greenpeace.org/argentina/"  =>  "Argentina (Español)",
	"http://www.greenpeace.org/australia"  =>  "Australia (English)",
	"http://www.greenpeace.at/"  =>  "Austria (Deutsch)",
	"http://www.greenpeace.org/belgium/"  =>  "Belgium (Nederlands/Français)",
	"http://www.greenpeace.org/brasil/"  =>  "Brazil (Português)",
	"http://www.greenpeace.org/canada"  =>  "Canada (English/Français)",
	"http://www.greenpeace.org/chile/"  =>  "Chile (Español)",
	"http://www.greenpeace.org/china/zh"  =>  "China Mainland (简体中文/English)",
	"http://www.greenpeace.cz/"  =>  "Czech Republic (Česky)",
	"http://www.greenpeace.dk"  =>  "Denmark (Dansk)",
	"http://www.greenpeace.org/australia"  =>  "Fiji (English)",
	"http://www.greenpeace.org/finland"  =>  "Finland (Suomea)",
	"http://www.greenpeace.org/france"  =>  "France (Français)",
	"http://www.greenpeace.de"  =>  "Germany (Deutsch)",
	"http://www.greenpeace.gr/"  =>  "Greece (Ελληνικά)",
	"http://www.greenpeace.org/hk/"  =>  "Hong Kong (繁體中文/English)",
	"http://www.greenpeace.hu/"  =>  "Hungary (Magyar)",
	"http://www.greenpeace.org/india/"  =>  "India (English)",
	"http://www.greenpeace.org/seasia/id/"  =>  "Indonesia (Indonesia)",
	"http://www.greenpeace.org/israel/"  =>  "Israel (עברית)",
	"http://www.greenpeace.it/new/"  =>  "Italy (Italiano)",
	"http://www.greenpeace.org/japan/"  =>  "Japan (日本語)",
	"http://www.greenpeace.org/lebanon/ar"  =>  "Lebanon (العربية)",
	"http://www.greenpeace.lu/"  =>  "Luxembourg (Français)",
	"http://www.greenpeace.org/mediterranean/"  =>  "Malta (English)",
	"http://www.greenpeace.org/mexico/"  =>  "Mexico (Español)",
	"http://www.greenpeace.nl/"  =>  "Netherlands (Nederlands)",
	"http://www.greenpeace.org.nz/"  =>  "New Zealand (English)",
	"http://www.greenpeace.no"  =>  "Norway (Norsk)",
	"http://www.greenpeace.org.au/"  =>  "Papua New Guinea (English)",
	"http://www.greenpeace.org/seasia/en/ph/"  =>  "Philippines (English)",
	"http://www.greenpeace.pl"  =>  "Poland (Polska)",
	"http://www.greenpeace.org/portugal/"  =>  "Portugal (Português)",
	"http://www.greenpeace.ro"  =>  "Romania (Român)",
	"http://www.greenpeace.org/russia/ru"  =>  "Russia (Русский)",
	"http://www.greenpeace.sk/"  =>  "Slovakia (Slovenčina)",
	"http://www.greenpeace.org/seasia/"  =>  "Southeast Asia (English)",
	"http://www.greenpeace.org/espana/"  =>  "Spain (Español)",
	"http://www.greenpeace.se/"  =>  "Sweden (Svenska)",
	"http://www.greenpeace.org/switzerland/de/"  =>  "Switzerland (Deutsch)",
	"http://www.greenpeace.org/switzerland/fr/"  =>  "Switzerland (Français)",
	"http://www.greenpeace.org/taiwan/ch"  =>  "Taiwan (繁體中文/English)",
	"http://www.greenpeace.org/seasia/th/"  =>  "Thailand (ไทย)",
	"http://www.greenpeace.org/turkey/"  =>  "Turkey (Türk)",
	"http://www.greenpeace.org.uk/"  =>  "United Kingdom (English)",
	"http://www.greenpeace.org/usa"  =>  "USA (English)"
	
);
?>
